
--GET_AGE_RANGE
CREATE OR REPLACE FUNCTION CASESTUDY_WORKING.PUBLIC.GET_AGE_RANGE("AGE" NUMBER(38,0))
RETURNS VARCHAR(16777216)
LANGUAGE SQL
AS '
CASE WHEN AGE<=40 THEN ''31-40'' 
    WHEN AGE<=50 THEN ''41-50''
    WHEN AGE<=60 THEN ''51-60''
    WHEN AGE<=70 THEN ''61-70''
    WHEN AGE<=80 THEN ''71-80''
    END
';

-- GET_RISK_PROFILE
CREATE OR REPLACE FUNCTION CASESTUDY_WORKING.PUBLIC.GET_RISK_PROFILE("CUSTOMER_ID" NUMBER(38,0))
RETURNS VARCHAR(16777216)
LANGUAGE SQL
AS '

        SELECT RP.RISK_PROFILE
        FROM RISK_PROFILE RP
        WHERE RP.RISK_PROFILE_ID = (
            SELECT ROUND(AVG(A.RISK_PROFILE_ID), 0)
            FROM CUSTOMER_ANSWERS CA
            JOIN ANSWERS A ON CA.QUESTION_ID = A.QUESTION_ID AND CA.ANSWER_ID = A.ANSWER_ID
            WHERE CA.CUSTOMER_ID = CUSTOMER_ID
        )
    
';

--GET_SEGMENT
CREATE OR REPLACE FUNCTION CASESTUDY_WORKING.PUBLIC.GET_SEGMENT("GENDER" VARCHAR(10), "AGE_RANGE" VARCHAR(20))
RETURNS NUMBER(38,0)
LANGUAGE SQL
AS '
CASE WHEN GENDER=''Male'' AND AGE_RANGE=''31-40'' THEN   1 
WHEN GENDER=''Female'' AND AGE_RANGE=''31-40'' THEN  2 
WHEN GENDER=''Male'' AND AGE_RANGE=''41-50'' THEN  3 
WHEN GENDER=''Female'' AND AGE_RANGE=''41-50'' THEN  4 
WHEN GENDER=''Male'' AND AGE_RANGE=''51-60'' THEN  5
 WHEN GENDER=''Female'' AND AGE_RANGE=''51-60'' THEN 6 
WHEN GENDER=''Male'' AND AGE_RANGE=''61-70'' THEN  7
WHEN GENDER=''Female'' AND AGE_RANGE=''61-70'' THEN   8
WHEN GENDER=''Male'' AND AGE_RANGE=''71-80'' THEN  9
WHEN GENDER=''Female'' AND AGE_RANGE=''71-80'' THEN  10
END
';

--GET_ASSET_VALUE_NAME
CREATE OR REPLACE FUNCTION CASESTUDY_WORKING.PUBLIC.GET_ASSET_VALUE_NAME("ASSET_OBJECTIVE_ID" NUMBER(38,0))
RETURNS VARCHAR(16777216)
LANGUAGE SQL
AS 'SELECT ASSET_OBJECTIVE_NAME FROM ASSET_OBJECTIVES WHERE ASSET_OBJECTIVE_ID = ASSET_OBJECTIVE_ID';

--GET_ASSET_VALUE
CREATE OR REPLACE FUNCTION CASESTUDY_WORKING.PUBLIC.GET_ASSET_VALUE("CUSTOMER_ID" NUMBER(38,0), "ASSET_OBJECTIVE_ID" NUMBER(38,0))
RETURNS NUMBER(38,0)
LANGUAGE SQL
AS 'SELECT TOTAL FROM CUSTOMER_ASSETS WHERE CUSTOMER_ID = CUSTOMER_ID AND ASSET_OBJECTIVE_ID = ASSET_OBJECTIVE_ID GROUP BY CUSTOMER_ID, ASSET_OBJECTIVE_ID,TOTAL ';