--Answers 
create or replace TABLE CASESTUDY_WORKING.PUBLIC.ANSWERS (
	QUESTION_ID NUMBER(38,0),
	ANSWER_ID NUMBER(38,0),
	ANSWER_TEXT VARCHAR(16777216),
	RISK_PROFILE_ID NUMBER(38,0),
	constraint PK_ANSWERS primary key (QUESTION_ID, ANSWER_ID),
	constraint FK_ANSWERS_QUESTION_ID foreign key (QUESTION_ID) references CASESTUDY_WORKING.PUBLIC.QUESTIONS(QUESTION_ID),
	constraint FK_ANSWERS_RISK_PROFILE_ID foreign key (RISK_PROFILE_ID) references CASESTUDY_WORKING.PUBLIC.RISK_PROFILE(RISK_PROFILE_ID)
);

--Asset Classes
create or replace TABLE CASESTUDY_WORKING.PUBLIC.ASSET_CLASSES (
	ASSET_CLASS VARCHAR(16777216),
	RISK_PROFILE_ID NUMBER(38,0),
	ASSET_CLASS_ID NUMBER(38,0),
	constraint PK_ASSET_CLASSES_ID primary key (ASSET_CLASS_ID),
	constraint FK_ASSET_CLASSES_RISK_PROFILE foreign key (RISK_PROFILE_ID) references CASESTUDY_WORKING.PUBLIC.RISK_PROFILE(RISK_PROFILE_ID)
);

--ASSET_OBJECTIVES
create or replace TABLE CASESTUDY_WORKING.PUBLIC.ASSET_OBJECTIVES (
	ASSET_OBJECTIVE_NAME VARCHAR(16777216),
	ASSET_OBJECTIVE_ID NUMBER(38,0),
	constraint PK_ASSET_OBJECTIVES primary key (ASSET_OBJECTIVE_ID)
);


--CUSTOMERS
create or replace TABLE CASESTUDY_WORKING.PUBLIC.CUSTOMERS (
	CUSTOMER_ID NUMBER(38,0),
	CONTACT_LAST_NAME VARCHAR(16777216),
	CONTACT_FIRST_NAME VARCHAR(16777216),
	STREET VARCHAR(16777216),
	CITY VARCHAR(16777216),
	STATE VARCHAR(16777216),
	ZIP NUMBER(38,0),
	COUNTRY VARCHAR(16777216),
	AGE NUMBER(38,0),
	MARITAL_STATUS VARCHAR(16777216),
	GENDER VARCHAR(16777216),
	NUMBER_OF_DEPENDENTS NUMBER(38,0),
	constraint PK_CUSTOMER primary key (CUSTOMER_ID)
);


--CUSTOMER_ANSWERS
create or replace TABLE CASESTUDY_WORKING.PUBLIC.CUSTOMER_ANSWERS (
	CUSTOMER_ID NUMBER(38,0),
	QUESTION_ID NUMBER(38,0),
	ANSWER_ID NUMBER(38,0),
	constraint PK_CUSTOMER_ANSWERS primary key (CUSTOMER_ID, QUESTION_ID, ANSWER_ID),
	constraint FK_CA_QA foreign key (QUESTION_ID, ANSWER_ID) references CASESTUDY_WORKING.PUBLIC.ANSWERS(QUESTION_ID,ANSWER_ID),
	constraint FK_CA_CUSTOMER_ID foreign key (CUSTOMER_ID) references CASESTUDY_WORKING.PUBLIC.CUSTOMERS(CUSTOMER_ID)
);


--CUSTOMER_ASSETS
create or replace TABLE CASESTUDY_WORKING.PUBLIC.CUSTOMER_ASSETS (
	CUSTOMER_ID NUMBER(38,0),
	ASSET_OBJECTIVE_ID NUMBER(38,0),
	TOTAL NUMBER(38,13),
	constraint PK_CUSTOMER_ASSETS primary key (CUSTOMER_ID, ASSET_OBJECTIVE_ID),
	constraint FK_CA_ASSET_OBJECTIVE_ID foreign key (ASSET_OBJECTIVE_ID) references CASESTUDY_WORKING.PUBLIC.ASSET_OBJECTIVES(ASSET_OBJECTIVE_ID),
	constraint FK_CA_CUSTOMER_ID foreign key (CUSTOMER_ID) references CASESTUDY_WORKING.PUBLIC.CUSTOMERS(CUSTOMER_ID)
);

--CUSTOMER_ENGAGEMENT_PREFERENCES

create or replace TABLE CASESTUDY_WORKING.PUBLIC.CUSTOMER_ENGAGEMENT_PREFERENCES (
	CUSTOMER_ID NUMBER(38,0),
	ENGAGEMENT_TYPE_ID NUMBER(38,0),
	FREQUENCY_ID NUMBER(38,0),
	constraint PK_CEP primary key (FREQUENCY_ID, CUSTOMER_ID, ENGAGEMENT_TYPE_ID),
	constraint FK_CEP_CUSTOMER_ID foreign key (CUSTOMER_ID) references CASESTUDY_WORKING.PUBLIC.CUSTOMERS(CUSTOMER_ID),
	constraint FK_CEP_ENGAGEMENT_TYPE_ID foreign key (ENGAGEMENT_TYPE_ID) references CASESTUDY_WORKING.PUBLIC.ENGAGEMENT_TYPES(ENGAGEMENT_TYPE_ID),
	constraint FK_CEP_FREQUENCY_ID foreign key (FREQUENCY_ID) references CASESTUDY_WORKING.PUBLIC.ENGAGEMENT_FREQUENCIES(FREQUENCY_ID)
);

--CUSTOMER_FUNDS
create or replace TABLE CASESTUDY_WORKING.PUBLIC.CUSTOMER_FUNDS (
	CUSTOMER_ID NUMBER(38,0) NOT NULL,
	FUND_ID NUMBER(38,0) NOT NULL,
	AMOUNT_INVESTED NUMBER(38,0),
	constraint PK_CF primary key (CUSTOMER_ID, FUND_ID),
	constraint FK_CF_CUSTOMER_ID foreign key (CUSTOMER_ID) references CASESTUDY_WORKING.PUBLIC.CUSTOMERS(CUSTOMER_ID),
	constraint FK_CA_FUND_ID foreign key (FUND_ID) references CASESTUDY_WORKING.PUBLIC.FUNDS(FUND_ID)
);

--CUSTOMER_SEGMENT
create or replace TABLE CASESTUDY_WORKING.PUBLIC.CUSTOMER_SEGMENT (
	CUSTOMER_ID NUMBER(38,0),
	SEGMENT_ID NUMBER(38,0)
);

--ENGAGEMENT_FREQUENCIES
create or replace TABLE CASESTUDY_WORKING.PUBLIC.ENGAGEMENT_FREQUENCIES (
	FREQUENCY_NAME VARCHAR(16777216),
	FREQUENCY_ID NUMBER(38,0),
	constraint PK_ENGAGEMENT_FREQUENCY_ID primary key (FREQUENCY_ID)
);

--ENGAGEMENT_TYPES

create or replace TABLE CASESTUDY_WORKING.PUBLIC.ENGAGEMENT_TYPES (
	ENGAGEMENT_TYPE_NAME VARCHAR(16777216),
	ENGAGEMENT_TYPE_ID NUMBER(38,0),
	constraint PK_ENGAGEMENT_TYPE primary key (ENGAGEMENT_TYPE_ID)
);

--FEE_STRUCTURES
create or replace TABLE CASESTUDY_WORKING.PUBLIC.FEE_STRUCTURES (
	ASSET_CLASS_ID NUMBER(38,0),
	FLAT_FEE NUMBER(38,0),
	PERCENTAGE_FEE NUMBER(38,4),
	constraint PK_FEE_STRUCTURES primary key (ASSET_CLASS_ID),
	constraint FK_FEE_STRUCTURES_ASSET_CLASS_ID foreign key (ASSET_CLASS_ID) references CASESTUDY_WORKING.PUBLIC.ASSET_CLASSES(ASSET_CLASS_ID)
);


--FUNDS
create or replace TABLE CASESTUDY_WORKING.PUBLIC.FUNDS (
	FUND_NAME VARCHAR(16777216),
	FUND_DESCRIPTION VARCHAR(16777216),
	MINIMUM_INVESTMENT_REQUIRED NUMBER(38,0),
	MAXIMUM_INVESTMENT_ALLOWED NUMBER(38,0),
	FUND_ID NUMBER(38,0),
	constraint PK_FUND_ID primary key (FUND_ID)
);

--FUND_ASSETS

create or replace TABLE CASESTUDY_WORKING.PUBLIC.FUND_ASSETS (
	FUND_ID NUMBER(38,0),
	ASSET_CLASS_ID NUMBER(38,0),
	PERCENT_OF_FUND NUMBER(38,0),
	constraint PK_FA primary key (FUND_ID, ASSET_CLASS_ID),
	constraint FK_FA_AC foreign key (ASSET_CLASS_ID) references CASESTUDY_WORKING.PUBLIC.ASSET_CLASSES(ASSET_CLASS_ID),
	constraint FK_FA_FUND_ID foreign key (FUND_ID) references CASESTUDY_WORKING.PUBLIC.FUNDS(FUND_ID)
);

--FUND_TARGETS
create or replace TABLE CASESTUDY_WORKING.PUBLIC.FUND_TARGETS (
	FUND_ID NUMBER(38,0),
	ASSET_OBJECTIVE_ID NUMBER(38,0),
	ENGAGEMENT_TYPE_ID NUMBER(38,0),
	FREQUENCY_ID NUMBER(38,0),
	TARGET_DESCRIPTION VARCHAR(16777216),
	constraint PK_FT primary key (FUND_ID),
	constraint FK_FT_ENGAGEMENT_TYPE_ID foreign key (ENGAGEMENT_TYPE_ID) references CASESTUDY_WORKING.PUBLIC.ENGAGEMENT_TYPES(ENGAGEMENT_TYPE_ID),
	constraint FK_FT_FREQUENCY_ID foreign key (FREQUENCY_ID) references CASESTUDY_WORKING.PUBLIC.ENGAGEMENT_FREQUENCIES(FREQUENCY_ID),
	constraint FK_FT_ASSET_OBJECTIVE_ID foreign key (ASSET_OBJECTIVE_ID) references CASESTUDY_WORKING.PUBLIC.ASSET_OBJECTIVES(ASSET_OBJECTIVE_ID),
	constraint FK_FT_FUND_ID foreign key (FUND_ID) references CASESTUDY_WORKING.PUBLIC.FUNDS(FUND_ID)
);


--QUESTIONS
create or replace TABLE CASESTUDY_WORKING.PUBLIC.QUESTIONS (
	QUESTION_SUBJECT VARCHAR(16777216),
	QUESTION_TEXT VARCHAR(16777216),
	QUESTION_ID NUMBER(38,0),
	constraint PK_QUESTION_ID primary key (QUESTION_ID)
);

--RISK_PROFILE

create or replace TABLE CASESTUDY_WORKING.PUBLIC.RISK_PROFILE (
	RISK_PROFILE VARCHAR(16777216),
	RISK_PROFILE_ID NUMBER(38,0),
	constraint PK_RISK_PROFILE primary key (RISK_PROFILE_ID)
);


--SEGMENTS
create or replace TABLE CASESTUDY_WORKING.PUBLIC.SEGMENTS (
	SEGMENT_ID NUMBER(38,0) NOT NULL autoincrement start 1 increment 1 noorder,
	RISK_PROFILE_ID NUMBER(38,0),
	ENGAGEMENT_TYPE_ID NUMBER(38,0),
	primary key (SEGMENT_ID),
	constraint FK_RISK_PROFILE_ID foreign key (RISK_PROFILE_ID) references CASESTUDY_WORKING.PUBLIC.RISK_PROFILE(RISK_PROFILE_ID),
	constraint FK_ENGAGEMENT_TYPE_ID foreign key (ENGAGEMENT_TYPE_ID) references CASESTUDY_WORKING.PUBLIC.ENGAGEMENT_TYPES(ENGAGEMENT_TYPE_ID)
);